# Site settings
title: Jar Full of Autumn Leaves
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   An archive of roads that were taken.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

paginate: 4

author: Your name

gems: [jekyll-paginate]
